version: '3.8'

x-rails-service: &rails-service
  build:
    context: .
  restart: on-failure
  environment:
    - RAILS_ENV=development
  stdin_open: true
  tty: true

services:
  ws:
    <<: *rails-service
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    env_file:
      - '.env'
    healthcheck:
      test: curl --fail http://localhost:3000/status || exit 1
      interval: 5s
      retries: 10
      timeout: 2s